# Generated by Django 3.0.3 on 2020-03-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='user_vote',
            field=models.IntegerField(default=0),
        ),
    ]
